### ISSUE TITLE
Suggestion - Allow users to add more sites

### ISSUE THREAD

**Issue by pmacca** [sneakaway-studio/stop-slide-scrolling#4]
Hello, this extension has saved my sanity.
There are other sites the silly mouse flips out on though.

Making this list editable would be cool -  https://github.com/sneakaway-studio/stop-slide-scrolling/blob/master/extension/manifest.json#L18

**Comment by omundy** [comment]
Hi, submit a pull request and I'll push it next time I update.

**Comment by omundy** [comment]
@pmacca the manifest isn't editable unfortunately. If you let me know what sites I can add them.
