### ISSUE TITLE
New chrome version update block scrolling in Sheets, Docs as well

### ISSUE THREAD

**Issue by ag211** [sneakaway-studio/stop-slide-scrolling#6]
With the latest Chrome update, scrolling is blocked on all other Google Work Apps outside of Slides. Hopefully, you can release an update soon.

**Comment by omundy** [comment]
Which urls?

**Comment by edhgoose** [comment]
I haven't seen the problem as wide as ag211, but the main one I see it on is https://docs.google.com/spreadsheets/.

There's an issue here too that reports it: https://chrome.google.com/webstore/detail/stop-slide-scrolling-in-g/cmpmjbfhpecollipohbphhgbohleeeon

**Comment by omundy** [comment]
Hi, thank you for the message. I have pushed the fix to the Chrome Web Store in version 0.1.4. Once they release that version this issue will go away.

**Comment by edhgoose** [comment]
I haven't seen the issue since the fix was pushed @omundy - thank you!
